# -*- coding:utf-8 -*-

# Database select test. 
#
# This script is auto generated by ngrinder.
#
# @author ${user.userName}
from java.sql import DriverManager
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from ${driverPath} import ${jdbcDriver}
from java.util import Random
from java.lang import System
 
test1 = Test(1, "Database select")
random = Random(long(System.nanoTime()))
 
# Load the JDBC driver.
DriverManager.registerDriver(${jdbcDriver}())
 
def getConnection():
    return DriverManager.getConnection(
        "${url}", "${account}", "${password}")
 
def ensureClosed(object):
    try: object.close()
    except: pass
 
# One time initialisation that cleans out old data.
connection = getConnection()
# statement = connection.createStatement()
 
# You must ensure that the table and records already exist in the database.
# statement.execute("create table ngrinder_select_temp(test_id integer, test_number integer)")
 
# ensureClosed(statement)
# ensureClosed(connection)
 
class TestRunner:
    def __call__(self):
        selectStatement = None
 
        try:
            selectStatement = connection.createStatement()
            tmpId = random.nextInt(1024)
            # test1.record(selectStatement)
            selectStatement = test1.wrap(selectStatement)
            selectStatement.execute("select * from ngrinder_select_temp where test_id=%d" % tmpId)

        finally:
            ensureClosed(selectStatement)
