# -*- coding:utf-8 -*-

# Database insert test. 
#
# This script is auto generated by ngrinder.
#
# @author ${user.userName}
from java.sql import DriverManager
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from ${driverPath} import ${jdbcDriver}
 
test1 = Test(1, "Database insert")
 
# Load the JDBC driver.
DriverManager.registerDriver(${jdbcDriver}())
 
def getConnection():
    return DriverManager.getConnection(
        "${url}", "${account}", "${password}")
 
def ensureClosed(object):
    try: object.close()
    except: pass
 
# One time initialisation that cleans out old data.
connection = getConnection()
statement = connection.createStatement()
 
try: statement.execute("drop table ngrinder_insert_temp")
except: pass
 
statement.execute("create table ngrinder_insert_temp(thread integer, run integer)")
 
ensureClosed(statement)
# ensureClosed(connection)
 
class TestRunner:
    def __call__(self):
        connection = None
        insertStatement = None
 
        try:
            insertStatement = connection.createStatement()
 
            insertStatement = test1.wrap(insertStatement)
            insertStatement.execute("insert into ngrinder_insert_temp values(%d, %d)" %
                                    (grinder.threadNumber, grinder.runNumber))
 

        finally:
            ensureClosed(insertStatement)
            ensureClosed(connection)