# -*- coding:utf-8 -*-

# Database update test. 
#
# This script is auto generated by ngrinder.
#
# @author ${user.userName}
from java.sql import DriverManager
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from ${driverPath} import ${jdbcDriver}
from java.util import Random
from java.lang import System
 
test1 = Test(1, "Database update")
random = Random(long(System.nanoTime()))
 
# Load the JDBC driver.
DriverManager.registerDriver(${jdbcDriver}())
 
def getConnection():
    return DriverManager.getConnection(
        "${url}", "${account}", "${password}")
 
def ensureClosed(object):
    try: object.close()
    except: pass
 
# One time initialisation that cleans out old data.
connection = getConnection()
# statement = connection.createStatement()
 
# You must ensure that the table and records already exist in the database.
# statement.execute("create table ngrinder_update_test(test_id integer, test_number integer)")
 
# ensureClosed(statement)
# ensureClosed(connection)
 
class TestRunner:
    def __call__(self):
        updateStatement = None
 
        try:
            updateStatement = connection.createStatement()
            tmpId = random.nextInt(10240)
            tmpNumber = random.nextInt(10240)
            updateStatement = test1.wrap(updateStatement)
            updateStatement.execute("update ngrinder_update_test set test_number=%d where test_id=%d" % (tmpId, tmpNumber))

        finally:
            ensureClosed(updateStatement)
